version: '2'

services:
         online:
              build: ../my-apps/online
              image: online:0.1
              container_name: online
         hours-in-between:
               build: ../my-apps/hours-in-between
               image: hours-in-between:0.1
               container_name: hours-in-between
         nginx-proxy:
              build: ../my-apps/nginx-proxy
              image: nginx-proxy:0.1
              container_name: nginx-proxy
              ports:
                   - "80:80"
~
